# Reference:
#   - https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # When to check for updates to GitHub Actions
      interval: "weekly"
      day: "thursday"
      time: "01:00"
      timezone: "Europe/London"
    labels:
      - "new: pull request"
      - "bot"
