version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_install:
      - sphinx-apidoc -Mfe -o ./docs/api ./lib/ncdata

conda:
  environment: requirements/readthedocs.yml

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
